name: Prisma Cloud scan and upload

on:
  push:
    branches:
      - main
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: "Install Opengrep"
        env:
          RELEASE_VERSION: "v1.0.0-alpha.11"
        run: |
              set -e
              echo "Download Opengrep"
              curl -sSfL \
                -o "/usr/local/bin/opengrep" \
                https://github.com/opengrep/opengrep/releases/download/${RELEASE_VERSION}/opengrep_manylinux_x86
              chmod +x /usr/local/bin/opengrep
              echo "Opengrep installed"
              opengrep --version
      
      - name: "Run Opengrep"
        run: opengrep scan --metrics=off --sarif-output ./output.sarif .

      - name: Upload to Prisma Cloud
        env:
          PRISMA_URL: ${{ secrets.PRISMA_URL }}
          PRISMA_USERNAME: ${{ secrets.PRISMA_USERNAME }}
          PRISMA_PASSWORD: ${{ secrets.PRISMA_PASSWORD }}
          PRISMA_REPO_ID: ${{ secrets.PRISMA_REPO_ID }}
        run: |
          # Logging in to Prisma Cloud and obtaining JWT token
          AUTH_RESPONSE=$(curl -L "$PRISMA_URL/login" \
                             -H 'Content-Type: application/json; charset=UTF-8' \
                             -H 'Accept: application/json; charset=UTF-8' \
                             -d '{
                                   "password": "'"${PRISMA_PASSWORD}"'",
                                   "username": "'"${PRISMA_USERNAME}"'"
                                 }')

          echo "AUTH_RESPONSE: $AUTH_RESPONSE"

          TOKEN=$(echo $AUTH_RESPONSE | jq -r '.token')
          MESSAGE=$(echo $AUTH_RESPONSE | jq -r '.message')

          echo "Token: $TOKEN"
          echo "Message: $MESSAGE"

          if [ -z "$TOKEN" ]; then
            echo "Error: Failed to retrieve token"
            exit 1
          fi

          UPLOAD_RESPONSE=$(curl -v -X POST "$PRISMA_URL/code/api/v2/uploads/uploadSarifFile" \
                          -H "Authorization: $TOKEN" \
                          -F "file=@./output.sarif;type=application/octet-stream" \
                          -F "repositoryId=$PRISMA_REPO_ID" \
                          -F "fileName=output.sarif")

          echo "Upload response: $UPLOAD_RESPONSE"
